#!/usr/bin/env python3
"""
workstation.py - Resolve and wire the "md workstation" for a project.

The md workstation is a folder outside the code repo that holds all Avengers +
BMAD + OpenSpec markdown for it, at <md-root>/<repo-name>-mds/. Each managed link
is a directory symlink in the project, ignored through .git/info/exclude so the
team's committed config and .gitignore stay untouched:

  bmad      BMAD's output_folder (default _bmad-output) -> <workstation>
  openspec  openspec/                                  -> <workstation>/openspec

Which links are managed is recorded in mdLinks. Without mdLinks (installs from
before managed links, or a plain `set`), only the bmad link is managed. bmad is
also managed whenever _bmad/ exists; openspec only once `--link openspec` asks.

State:
  <project>/.avengers/settings.json  mdWorkstation, mdLinks, mdRepointDeclined
  ~/.avengers/workstations.json      {"root": "<md-root>", "repos": {"<remote-key>": "<path>"}}

Commands:
  resolve [--link L]                   Report where the workstation is (JSON)
  set --path P [--root R] [--in-repo] [--link L]
                                       Wire the workstation (symlinks, settings, exclude,
                                       .claude/rules/avengers-kb.md)
  migrate [--path P] [--untrack] [--link L]
                                       Move an in-repo link folder into the workstation
  check-config                         List BMAD path keys that resolve outside output_folder
  repoint-config --key K [--decline]   Re-point one key under output_folder (or record a decline)
  md-status                            Dirty files under the workstation in its md git repo
  grant-path                           Realpath of the workstation for additionalDirectories
  kb-rules                             (Re)write .claude/rules/avengers-kb.md
  unlink                               Remove the symlinks, settings, avengers-kb.md and
                                       exclude lines

Exit codes:
  0 = success
  1 = error
  2 = no-op (see each subcommand's --help)
"""
from __future__ import annotations

import argparse
import filecmp
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_OUTPUT = "_bmad-output"
IN_REPO = "in-repo"
CONFIG_FILES = {
    "bmm": Path("_bmad") / "bmm" / "config.yaml",
    "tea": Path("_bmad") / "tea" / "config.yaml",
}
CORE_CONFIG = Path("_bmad") / "core" / "config.yaml"
PROJECT_SETTINGS = Path(".avengers") / "settings.json"
KB_RULES = Path(".claude") / "rules" / "avengers-kb.md"
PATH_KEY_SUFFIXES = ("_folder", "_artifacts", "_knowledge", "_output", "_path", "_dir")
AUTOMATOR = "bmad-story-automator"
WS_SUFFIX = "-mds"
LINKS = ("bmad", "openspec")
OPENSPEC_DIR = "openspec"
LINK_LABELS = {"bmad": "BMAD output, Hulk specs, KB", "openspec": "OpenSpec specs and changes"}

KB_RULES_TEMPLATE = """\
# Avengers Dev - Knowledge Base
# Generated by workstation.py (set, kb-rules) and bmad-kb.py (stamp).
# Machine-specific; excluded via .git/info/exclude. Do not edit by hand.

This repo's markdown artifacts ({what}) live in the md
workstation at `{ws}`; {links}. Default `rg`,
`grep -r` and `find` do not follow {that}, so a search from the repo root
misses these files. Search by explicit path ({paths} or `{ws}`) -- with the
Grep/Glob tools, pass that path -- or use `grep -R` / `find -L`.
"""

UNTRACK_WARNING = (
    "WARNING: --untrack runs `git rm -r --cached` on {rel}. Once that removal is committed "
    "and pushed, every teammate who pulls LOSES their working copy of {rel}. Leave the "
    "untrack uncommitted until the team has agreed on it."
)


class WSError(Exception):
    """Unrecoverable error; main() prints it to stderr and exits 1."""


# --------------------------------------------------------------------------- json io

def load_json(path: Path) -> dict:
    """Load a JSON object. Malformed files are backed up to <name>.json.bak."""
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError("not a JSON object")
        return data
    except (ValueError, UnicodeDecodeError) as exc:
        backup = path.with_suffix(".json.bak")
        try:
            shutil.copy2(path, backup)
        except OSError as copy_exc:
            raise WSError(f"malformed {path} and cannot back it up: {copy_exc}") from exc
        print(f"WARNING: malformed JSON in {path} ({exc}); backed up to {backup.name}",
              file=sys.stderr)
        return {}


def save_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def registry_path() -> Path:
    return Path.home() / ".avengers" / "workstations.json"


# --------------------------------------------------------------------------- git

def run_git(cwd: Path, *args: str) -> subprocess.CompletedProcess | None:
    try:
        return subprocess.run(["git", "-C", str(cwd), *args],
                              capture_output=True, text=True, check=False)
    except OSError:
        return None


def git_out(cwd: Path, *args: str) -> str | None:
    proc = run_git(cwd, *args)
    if proc is None or proc.returncode != 0:
        return None
    return proc.stdout.strip()


def git_toplevel(cwd: Path) -> Path | None:
    out = git_out(cwd, "rev-parse", "--show-toplevel")
    return Path(out) if out else None


def normalize_remote(url: str) -> str:
    """Normalize a remote URL to host/path: host lowercased, user@, port and .git stripped."""
    url = url.strip()
    scp = re.match(r"^(?:[^@/]+@)?([^:/]+):(?!//)(.+)$", url)
    if "://" in url:
        _, rest = url.split("://", 1)
        hostpart, _, path = rest.partition("/")
        host = hostpart.rsplit("@", 1)[-1].split(":", 1)[0]
        if not host:  # file:///abs/path
            return os.path.normpath("/" + path)
    elif scp and not url.startswith("/"):
        host, path = scp.group(1), scp.group(2)
    else:
        return os.path.normpath(url)
    path = path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    return f"{host.lower()}/{path}"


def remote_key(project_dir: Path) -> tuple[str | None, str | None]:
    """Return (remote_key, repo_name). origin, then upstream, then first alphabetically.

    With no remote the key is the realpath of the git common dir (shared by worktrees).
    """
    remotes = (git_out(project_dir, "remote") or "").split()
    if remotes:
        chosen = next((r for r in ("origin", "upstream") if r in remotes), sorted(remotes)[0])
        url = git_out(project_dir, "remote", "get-url", chosen)
        if url:
            key = normalize_remote(url)
            return key, key.rstrip("/").rsplit("/", 1)[-1] or None
    common = git_out(project_dir, "rev-parse", "--path-format=absolute", "--git-common-dir")
    if not common:
        return None, None
    common_path = Path(os.path.realpath(common))
    name = common_path.parent.name if common_path.name == ".git" else common_path.name
    if name.endswith(".git"):
        name = name[:-4]
    return str(common_path), name


def exclude_file(project_dir: Path) -> Path | None:
    out = git_out(project_dir, "rev-parse", "--path-format=absolute", "--git-path", "info/exclude")
    return Path(out) if out else None


def exclude_patterns(project_dir: Path, links: list[Path]) -> list[str]:
    """Root-anchored patterns for the links + avengers-kb.md, no trailing slash (a trailing
    slash never matches a symlink)."""
    top = git_toplevel(project_dir)
    if top is None:
        return []
    top = Path(os.path.realpath(top))
    base = Path(os.path.realpath(project_dir))
    patterns = []
    for target in [*links, project_dir / KB_RULES]:
        if not is_within(target, project_dir):
            continue
        lexical = base / target.relative_to(project_dir)
        try:
            rel = lexical.relative_to(top).as_posix()
        except ValueError:
            continue
        patterns.append("/" + rel)
    return patterns


def git_tracked(project_dir: Path, output: Path) -> list[str]:
    proc = run_git(project_dir, "ls-files", "-z", "--", str(output.relative_to(project_dir)))
    if proc is None or proc.returncode != 0:
        return []
    return [entry for entry in proc.stdout.split("\0") if entry]


# --------------------------------------------------------------------------- bmad config

def _strip_value(raw: str) -> str:
    """Strip quotes and inline comments from a flat YAML scalar."""
    raw = raw.strip()
    if raw[:1] in ("'", '"'):
        quote = raw[0]
        end = raw.find(quote, 1)
        return raw[1:end] if end != -1 else raw[1:]
    return re.split(r"\s+#", raw, maxsplit=1)[0].strip()


def parse_flat_yaml(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return result
    for line in text.splitlines():
        if not line or line[0].isspace() or line.lstrip().startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if sep and (value := _strip_value(value)):
            result[key.strip()] = value
    return result


def expand(value: str, project_dir: Path, output: Path | None = None) -> Path:
    """Expand {project-root}/{output_folder} and normalize lexically (symlinks not followed)."""
    value = value.replace("{project-root}", str(project_dir))
    if output is not None:
        value = value.replace("{output_folder}", str(output))
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = project_dir / path
    return Path(os.path.normpath(path))


def output_folder(project_dir: Path) -> Path:
    for rel in (CONFIG_FILES["bmm"], CORE_CONFIG):
        value = parse_flat_yaml(project_dir / rel).get("output_folder")
        if value:
            return expand(value, project_dir)
    return project_dir / DEFAULT_OUTPUT


def is_within(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


# --------------------------------------------------------------------------- resolve

def project_settings(project_dir: Path) -> dict:
    return load_json(project_dir / PROJECT_SETTINGS)


def symlink_state(link: Path, target: Path | None) -> str:
    if link.is_symlink():
        if not link.exists():
            return "dangling"
        if target is not None and os.path.realpath(link) != os.path.realpath(target):
            return "mismatch"
        return "ok"
    if link.is_dir():
        return "real_dir"
    return "missing"


def link_names(project_dir: Path, settings: dict, extra: tuple[str, ...] = ()) -> list[str]:
    """Names of the managed links, in LINKS order.

    mdLinks recorded: those, plus bmad when _bmad/ exists. Not recorded (installs from
    before managed links): bmad alone for a plain call; with `extra` (e.g. --link
    openspec), bmad only when _bmad/ exists or a workstation is already wired.
    """
    recorded = settings.get("mdLinks")
    has_bmad = (project_dir / "_bmad").is_dir()
    if isinstance(recorded, list):
        names = {name for name in recorded if name in LINKS}
        if has_bmad:
            names.add("bmad")
    elif extra:
        wired = settings.get("mdWorkstation")
        names = {"bmad"} if has_bmad or (isinstance(wired, str) and wired and wired != IN_REPO) \
            else set()
    else:
        names = {"bmad"}
    names.update(extra)
    return [name for name in LINKS if name in names]


def link_map(project_dir: Path, ws: Path | None,
             names: list[str]) -> dict[str, tuple[Path, Path | None]]:
    """{name: (link in the project, target in the workstation)}."""
    links: dict[str, tuple[Path, Path | None]] = {}
    for name in names:
        if name == "bmad":
            links[name] = (output_folder(project_dir), ws)
        else:
            links[name] = (project_dir / OPENSPEC_DIR, ws / OPENSPEC_DIR if ws else None)
    return links


def managed_links(project_dir: Path, ws: Path | None, settings: dict,
                  extra: tuple[str, ...] = ()) -> dict[str, tuple[Path, Path | None]]:
    return link_map(project_dir, ws, link_names(project_dir, settings, extra))


def resolve(project_dir: Path, extra: tuple[str, ...] = ()) -> dict:
    settings = project_settings(project_dir)
    registry = load_json(registry_path())
    key, repo_name = remote_key(project_dir)
    root = registry.get("root")
    output = output_folder(project_dir)
    name = repo_name or project_dir.name
    report = {"state": "missing", "path": None, "source": None, "root": root,
              "remote_key": key, "repo_name": name,
              "suggested_path": str(Path(root) / f"{name}{WS_SUFFIX}") if root else None,
              "output_folder": str(output), "symlink": None, "symlinks": {}}

    recorded = settings.get("mdWorkstation")
    registered = (registry.get("repos") or {}).get(key) if key else None
    if recorded == IN_REPO:
        report.update(state="in_repo", source="project")
    elif recorded:
        report.update(path=recorded, source="project")
    elif registered:
        report.update(path=registered, source="registry")
    elif report["suggested_path"] and Path(report["suggested_path"]).is_dir():
        report.update(state="guess", path=report["suggested_path"], source="guess")

    if report["path"] and report["state"] == "missing":
        report["state"] = "ok" if Path(report["path"]).is_dir() else "broken"

    target = Path(report["path"]) if report["path"] else None
    report["symlink"] = symlink_state(output, target)
    report["symlinks"] = {name: symlink_state(link, link_target) for name, (link, link_target)
                          in managed_links(project_dir, target, settings, extra).items()}
    if report["state"] == "ok" and "dangling" in report["symlinks"].values():
        report["state"] = "broken"
    return report


def require_workstation(project_dir: Path, path: str | None) -> Path:
    if path:
        return Path(os.path.normpath(Path(path).expanduser().absolute()))
    report = resolve(project_dir)
    if report["state"] != "ok":
        raise WSError(f"workstation state is '{report['state']}'; pass --path or run `set` first")
    return Path(report["path"])


# --------------------------------------------------------------------------- set

def automator_installed(project_dir: Path) -> bool:
    return any((base / ".claude" / "skills" / AUTOMATOR).is_dir()
               for base in (Path.home(), project_dir))


def add_exclude_lines(project_dir: Path, patterns: list[str], dry_run: bool) -> list[str]:
    path = exclude_file(project_dir)
    if path is None or not patterns:
        return []
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    missing = [p for p in patterns if p not in existing]
    if missing and not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = existing + missing
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return missing


def remove_exclude_lines(project_dir: Path, patterns: list[str], dry_run: bool) -> list[str]:
    path = exclude_file(project_dir)
    if path is None or not path.exists():
        return []
    existing = path.read_text(encoding="utf-8").splitlines()
    removed = [p for p in patterns if p in existing]
    if removed and not dry_run:
        kept = [line for line in existing if line not in removed]
        path.write_text("\n".join(kept) + ("\n" if kept else ""), encoding="utf-8")
    return removed


def other_worktrees(project_dir: Path) -> list[Path]:
    """Toplevels of the other worktrees sharing this clone's .git/info/exclude."""
    proc = run_git(project_dir, "worktree", "list", "--porcelain")
    top = git_toplevel(project_dir)
    if proc is None or proc.returncode != 0 or top is None:
        return []
    mine = os.path.realpath(top)
    paths = [Path(line[len("worktree "):]) for line in proc.stdout.splitlines()
             if line.startswith("worktree ")]
    return [p for p in paths if os.path.realpath(p) != mine]


def patterns_in_use(project_dir: Path, patterns: list[str]) -> dict[str, str]:
    """Patterns another worktree still needs: {pattern: worktree path}."""
    in_use: dict[str, str] = {}
    for tree in other_worktrees(project_dir):
        for pattern in patterns:
            target = tree / pattern.lstrip("/")
            if pattern not in in_use and (target.is_symlink() or target.exists()):
                in_use[pattern] = str(tree)
    return in_use


def kb_rules_content(project_dir: Path, ws: Path, names: list[str] | None = None) -> str:
    """The search hint, naming each managed link (defaults to the recorded links)."""
    if names is None:
        names = link_names(project_dir, project_settings(project_dir))
    real_ws = Path(os.path.realpath(ws))
    rels, clauses = [], []
    for name, (link, _) in link_map(project_dir, ws, names).items():
        rel = _display(link, project_dir)
        rels.append(f"`{rel}/...`")
        clauses.append(f"`{rel}` in the repo is a symlink to it" if name == "bmad"
                       else f"`{rel}` in the repo is a symlink to its `{OPENSPEC_DIR}/` folder")
    content = KB_RULES_TEMPLATE.format(
        what=", ".join(LINK_LABELS[name] for name in names) or "Avengers state",
        ws=real_ws,
        links="; ".join(clauses) or "nothing in the repo links to it",
        that="that symlink" if len(clauses) == 1 else "those symlinks",
        paths=", ".join(rels) if rels else "the workstation path",
    )
    context = real_ws / "project-context.md"
    if context.is_file():
        content += f"\n@{context}\n"
    return content


def write_kb_rules(project_dir: Path, ws: Path, dry_run: bool,
                   names: list[str] | None = None) -> bool:
    """Write .claude/rules/avengers-kb.md. Returns True when the content changes."""
    rules = project_dir / KB_RULES
    content = kb_rules_content(project_dir, ws, names)
    if rules.is_file() and rules.read_text(encoding="utf-8") == content:
        return False
    if not dry_run:
        rules.parent.mkdir(parents=True, exist_ok=True)
        rules.write_text(content, encoding="utf-8")
    return True


def recorded_workstation(project_dir: Path) -> Path | None:
    value = project_settings(project_dir).get("mdWorkstation")
    return Path(value) if isinstance(value, str) and value and value != IN_REPO else None


def cmd_kb_rules(project_dir: Path, dry_run: bool) -> int:
    ws = recorded_workstation(project_dir)
    if ws is None or not ws.is_dir():
        raise WSError("no md workstation recorded for this project (or it is missing)")
    if not write_kb_rules(project_dir, ws, dry_run):
        print(f"{KB_RULES.as_posix()} is up to date (no-op)", file=sys.stderr)
        return 2
    if dry_run:
        print(kb_rules_content(project_dir, ws), end="")
    else:
        print(f"Wrote {KB_RULES.as_posix()}")
    return 0


def unwire(project_dir: Path, dry_run: bool) -> dict:
    """Remove each managed link's symlink, avengers-kb.md and (if unshared) the exclude lines.

    Never touches a real directory, the workstation contents, or the home registry.
    """
    links = [link for link, _ in managed_links(project_dir, recorded_workstation(project_dir),
                                               project_settings(project_dir)).values()]
    actions: list[str] = []
    for link in links:
        if link.is_symlink():
            actions.append(f"remove symlink {_display(link, project_dir)}")
    rules = project_dir / KB_RULES
    if rules.is_file():
        actions.append(f"remove {KB_RULES.as_posix()}")
    patterns = exclude_patterns(project_dir, links)
    present = remove_exclude_lines(project_dir, patterns, dry_run=True)
    kept = patterns_in_use(project_dir, present)
    removable = [p for p in present if p not in kept]
    if removable:
        actions.append("remove " + ", ".join(removable) + " from .git/info/exclude")
    if not dry_run:
        for link in links:
            if link.is_symlink():
                link.unlink()
        if rules.is_file():
            rules.unlink()
        remove_exclude_lines(project_dir, removable, dry_run=False)
    return {"actions": actions, "exclude_kept": kept}


def _display(path: Path, project_dir: Path) -> str:
    return path.relative_to(project_dir).as_posix() if is_within(path, project_dir) \
        else str(path)


def _kept_note(kept: dict[str, str]) -> None:
    for pattern, tree in kept.items():
        print(f"NOTE: kept {pattern} in .git/info/exclude; worktree {tree} still uses it",
              file=sys.stderr)


def collision(registry: dict, key: str | None, ws: Path) -> str | None:
    for other_key, other_path in (registry.get("repos") or {}).items():
        if other_key != key and os.path.normpath(other_path) == os.path.normpath(ws):
            return other_key
    return None


def suggest_name(key: str | None, ws: Path) -> Path:
    parts = (key or "").strip("/").split("/")
    org = parts[-2] if len(parts) >= 2 else "org"
    repo = parts[-1] if parts and parts[-1] else ws.name
    return ws.parent / f"{org}-{repo}{WS_SUFFIX}"


def validate_target(project_dir: Path, ws: Path) -> str | None:
    """Checks shared by set and migrate. Returns the remote key."""
    real_ws, real_project = Path(os.path.realpath(ws)), Path(os.path.realpath(project_dir))
    if is_within(real_ws, real_project):
        raise WSError(f"workstation {ws} is inside the project; choose a folder outside the repo")
    if is_within(real_project, real_ws):
        raise WSError(f"workstation {ws} contains the project; choose a folder outside the repo")
    if ws.exists() and not ws.is_dir():
        raise WSError(f"workstation {ws} exists and is not a directory")
    key, _ = remote_key(project_dir)
    clash = collision(load_json(registry_path()), key, ws)
    if clash:
        raise WSError(f"{ws} is already registered to {clash}; use a distinct folder such as "
                      f"{suggest_name(key, ws)}")
    return key


def cmd_set(project_dir: Path, path: str | None, root: str | None, in_repo: bool,
            dry_run: bool, extra: tuple[str, ...] = ()) -> int:
    code, payload = do_set(project_dir, path, root, in_repo, dry_run, extra)
    if payload is not None:
        print(json.dumps(payload, indent=2))
    return code


def migrate_hint(name: str) -> str:
    return "migrate" if name == "bmad" else f"migrate --link {name}"


def check_link(project_dir: Path, name: str, link: Path, target: Path) -> str:
    """Refuse a link that set cannot wire. Returns its symlink_state."""
    if not is_within(link, project_dir):
        raise WSError(f"output_folder {link} is outside the project; not supported")
    rel = link.relative_to(project_dir).as_posix()
    tracked = git_tracked(project_dir, link)
    if tracked:
        raise WSError(f"{rel} is tracked in git ({len(tracked)} file(s)); "
                      f"run `{migrate_hint(name)} --untrack` instead (read its warning first)")
    state = symlink_state(link, target)
    if state == "real_dir":
        if any(link.iterdir()):
            raise WSError(f"{rel} is a non-empty directory; run `{migrate_hint(name)}` to move "
                          "it into the workstation")
    elif link.exists() and not link.is_symlink():
        raise WSError(f"{rel} exists and is not a directory")
    return state


def do_set(project_dir: Path, path: str | None, root: str | None, in_repo: bool,
           dry_run: bool, extra: tuple[str, ...] = ()) -> tuple[int, dict | None]:
    settings_file = project_dir / PROJECT_SETTINGS
    if in_repo:
        settings = project_settings(project_dir)
        removed = unwire(project_dir, dry_run)
        _kept_note(removed["exclude_kept"])
        actions = list(removed["actions"])
        if settings.get("mdWorkstation") != IN_REPO:
            actions.append("record mdWorkstation: in-repo")
        if "mdLinks" in settings:
            actions.append(f"remove mdLinks from {PROJECT_SETTINGS.as_posix()}")
        if not actions:
            print("in-repo choice already recorded (no-op)", file=sys.stderr)
            return 2, None
        if not dry_run:
            settings["mdWorkstation"] = IN_REPO
            settings.pop("mdLinks", None)
            save_json(settings_file, settings)
        return 0, {"actions": actions, "exclude_kept": removed["exclude_kept"],
                   "dry_run": dry_run}
    if not path and root:
        _, repo_name = remote_key(project_dir)
        path = str(Path(root).expanduser() / f"{repo_name or project_dir.name}{WS_SUFFIX}")
    if not path:
        raise WSError("set needs --path or --root (or --in-repo)")

    ws = Path(os.path.normpath(Path(path).expanduser().absolute()))
    key = validate_target(project_dir, ws)
    settings = project_settings(project_dir)
    links = managed_links(project_dir, ws, settings, extra)
    names = list(links)
    # Check every link before changing anything.
    states = {name: check_link(project_dir, name, link, target)
              for name, (link, target) in links.items()}

    registry = load_json(registry_path())
    actions: list[str] = []
    if not ws.is_dir() or not (ws / "avengers").is_dir():
        actions.append(f"create {ws}/avengers/")
    for name, (_, target) in links.items():
        if name != "bmad" and not target.is_dir():
            actions.append(f"create {target}/")
    if settings.get("mdWorkstation") != str(ws):
        actions.append(f"set mdWorkstation in {PROJECT_SETTINGS.as_posix()}")
    if settings.get("mdLinks") != names:
        actions.append(f"record mdLinks: {', '.join(names) or '(none)'}")
    new_root = root or registry.get("root") or str(ws.parent)
    if key and ((registry.get("repos") or {}).get(key) != str(ws)
                or registry.get("root") != new_root):
        actions.append(f"register {key} in ~/.avengers/workstations.json")
    for name, (link, target) in links.items():
        if states[name] != "ok":
            actions.append(f"symlink {_display(link, project_dir)} -> {target}")
    patterns = exclude_patterns(project_dir, [link for link, _ in links.values()])
    pending = add_exclude_lines(project_dir, patterns, dry_run=True)
    if pending:
        actions.append("add " + ", ".join(pending) + " to .git/info/exclude")
    rules_file = project_dir / KB_RULES
    if not rules_file.is_file() or rules_file.read_text(encoding="utf-8") != \
            kb_rules_content(project_dir, ws, names):
        actions.append(f"write {KB_RULES.as_posix()}")
    if not key:
        print("WARNING: not a git repository; the workstation is recorded for this project only",
              file=sys.stderr)

    if not actions:
        print(f"workstation already set to {ws} (no-op)", file=sys.stderr)
        return 2, None

    if not dry_run:
        (ws / "avengers").mkdir(parents=True, exist_ok=True)
        settings["mdWorkstation"] = str(ws)
        settings["mdLinks"] = names
        save_json(settings_file, settings)
        if key:
            registry.setdefault("repos", {})[key] = str(ws)
            registry["root"] = new_root
            save_json(registry_path(), registry)
        for name, (link, target) in links.items():
            if states[name] == "ok":
                continue
            target.mkdir(parents=True, exist_ok=True)  # the target exists before the link
            if states[name] == "real_dir":
                link.rmdir()
            elif link.is_symlink():
                link.unlink()
            link.parent.mkdir(parents=True, exist_ok=True)
            link.symlink_to(target, target_is_directory=True)
        add_exclude_lines(project_dir, patterns, dry_run=False)
        write_kb_rules(project_dir, ws, dry_run=False, names=names)

    if "bmad" in links and automator_installed(project_dir):
        print(f"WARNING: {AUTOMATOR} is installed. It rejects artifact paths that resolve "
              "outside the repo root, so it will not work with a workstation. The Avengers "
              "relay does not use it.", file=sys.stderr)
    return 0, {"path": str(ws), "links": names, "actions": actions, "dry_run": dry_run}


# --------------------------------------------------------------------------- migrate

def _conflict_name(dest: Path) -> Path:
    n = 1
    while True:
        tag = ".conflict" if n == 1 else f".conflict-{n}"
        candidate = dest.with_name(f"{dest.stem}{tag}{dest.suffix}")
        if not candidate.exists():
            return candidate
        n += 1


def plan_moves(src: Path, dest: Path, moves: list[tuple[Path, Path]]) -> None:
    """Merge src into dest. Identical files are dropped; differing ones get a .conflict name."""
    for entry in sorted(src.iterdir()):
        target = dest / entry.name
        if not target.exists() and not target.is_symlink():
            moves.append((entry, target))
        elif entry.is_dir() and not entry.is_symlink() and target.is_dir():
            plan_moves(entry, target, moves)
        elif entry.is_file() and target.is_file() and filecmp.cmp(entry, target, shallow=False):
            moves.append((entry, None))
        else:
            moves.append((entry, _conflict_name(target)))


def cmd_migrate(project_dir: Path, path: str | None, root: str | None, untrack: bool,
                dry_run: bool, link_name: str = "bmad") -> int:
    ws = require_workstation(project_dir, path)
    validate_target(project_dir, ws)
    output, target = link_map(project_dir, ws, [link_name])[link_name]
    if not is_within(output, project_dir):
        raise WSError(f"output_folder {output} is outside the project; not supported")
    rel_out = output.relative_to(project_dir).as_posix()
    if output.is_symlink() or not output.is_dir():
        print(f"{rel_out} is not an in-repo directory; nothing to migrate (no-op). "
              "Run `set` to create or repair the symlink.", file=sys.stderr)
        return 2

    tracked = git_tracked(project_dir, output)
    if tracked:
        print(UNTRACK_WARNING.format(rel=rel_out), file=sys.stderr)
        if not untrack:
            raise WSError(f"{rel_out} is tracked in git ({len(tracked)} file(s)); "
                          "re-run with --untrack once you accept the warning above")

    moves: list[tuple[Path, Path | None]] = []
    plan_moves(output, target, moves)
    report = {
        "path": str(ws),
        "link": link_name,
        "untracked": len(tracked) if tracked else 0,
        "moves": [{"from": str(s.relative_to(project_dir)),
                   "to": str(d) if d else None} for s, d in moves],
        "conflicts": [str(d) for s, d in moves if d and ".conflict" in d.name],
        "dry_run": dry_run,
    }
    if dry_run:
        print(json.dumps(report, indent=2))
        return 0

    target.mkdir(parents=True, exist_ok=True)
    for source, dest in moves:
        if dest is None:
            source.unlink()
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), str(dest))
    leftovers = [p for p in output.rglob("*") if not p.is_dir() or p.is_symlink()]
    if leftovers:
        raise WSError(f"{rel_out} still holds {len(leftovers)} entr(ies) after the move; "
                      "not removing it")
    shutil.rmtree(output)  # only empty directories remain after the moves

    # Untrack last: a failure here leaves the files safe in the workstation.
    if tracked:
        proc = run_git(project_dir, "rm", "-r", "--cached", "-q", "--", rel_out)
        if proc is None or proc.returncode != 0:
            raise WSError(f"files moved to {ws}, but git rm --cached failed: "
                          f"{proc.stderr.strip() if proc else 'no git'}; untrack {rel_out} "
                          "by hand, then run `set`")

    code, set_payload = do_set(project_dir, str(ws), root, False, False, (link_name,))
    report["set"] = set_payload
    print(json.dumps(report, indent=2))
    return 1 if code == 1 else 0


# --------------------------------------------------------------------------- config keys

def is_path_key(key: str, value: str) -> bool:
    return "{project-root}" in value or "{output_folder}" in value or key.endswith(
        PATH_KEY_SUFFIXES)


def suggested_value(project_dir: Path, output: Path, key: str) -> str:
    rel = output.relative_to(project_dir).as_posix()
    return "{project-root}/" + rel + "/" + key.replace("_", "-")


def outside_keys(project_dir: Path) -> list[dict]:
    output = output_folder(project_dir)
    if not is_within(output, project_dir):
        raise WSError(f"output_folder {output} is outside the project; the md workstation "
                      "needs an in-repo output_folder (e.g. _bmad-output)")
    declined = set(project_settings(project_dir).get("mdRepointDeclined") or [])
    found = []
    for module, rel in CONFIG_FILES.items():
        for key, value in parse_flat_yaml(project_dir / rel).items():
            if key == "output_folder" or not is_path_key(key, value):
                continue
            resolved = expand(value, project_dir, output)
            if is_within(resolved, output):
                continue
            found.append({"module": module, "file": rel.as_posix(), "key": key, "value": value,
                          "resolved": str(resolved),
                          "suggested": suggested_value(project_dir, output, key),
                          "declined": key in declined})
    return found


def cmd_check_config(project_dir: Path) -> int:
    if not (project_dir / "_bmad").is_dir():
        raise WSError("_bmad/ not found; run `npx bmad-method install`")
    found = outside_keys(project_dir)
    print(json.dumps({"output_folder": str(output_folder(project_dir)), "outside": found},
                     indent=2))
    return 2 if found else 0


def _rewrite_line(line: str, key: str, new_value: str) -> str:
    """Replace a `key: value  # comment` line's value, keeping the inline comment."""
    _, _, raw = line.partition(":")
    raw = raw.strip()
    comment = ""
    if raw[:1] in ("'", '"'):
        end = raw.find(raw[0], 1)
        rest = raw[end + 1:] if end != -1 else ""
        if (match := re.search(r"\s+#.*$", rest)):
            comment = match.group(0)
    elif (match := re.search(r"\s+#.*$", raw)):
        comment = match.group(0)
    return f'{key}: "{new_value}"{comment}'


def cmd_repoint(project_dir: Path, key: str, decline: bool, dry_run: bool) -> int:
    matches = [entry for entry in outside_keys(project_dir) if entry["key"] == key]
    if decline:
        settings = project_settings(project_dir)
        declined = list(settings.get("mdRepointDeclined") or [])
        if key in declined:
            print(f"'{key}' decline already recorded (no-op)", file=sys.stderr)
            return 2
        if not dry_run:
            settings["mdRepointDeclined"] = [*declined, key]
            save_json(project_dir / PROJECT_SETTINGS, settings)
        print(json.dumps({"declined": key, "dry_run": dry_run}, indent=2))
        return 0
    if not matches:
        known = any(key in parse_flat_yaml(project_dir / rel) for rel in CONFIG_FILES.values())
        if not known:
            raise WSError(f"key '{key}' not found in the bmm or tea config")
        print(f"'{key}' already resolves inside output_folder (no-op)", file=sys.stderr)
        return 2

    changes = []
    for entry in matches:
        cfg = project_dir / entry["file"]
        lines = cfg.read_text(encoding="utf-8").splitlines(keepends=True)
        pattern = re.compile(rf"^{re.escape(key)}\s*:")
        for i, line in enumerate(lines):
            if pattern.match(line):
                ending = "\n" if line.endswith("\n") else ""
                new_line = _rewrite_line(line.rstrip("\r\n"), key, entry["suggested"])
                changes.append({"file": entry["file"], "old": line.rstrip("\r\n"),
                                "new": new_line})
                lines[i] = new_line + ending
                break
        if not dry_run:
            shutil.copy2(cfg, cfg.with_name(cfg.name + ".bak"))
            cfg.write_text("".join(lines), encoding="utf-8")
    print(json.dumps({"key": key, "changes": changes, "dry_run": dry_run,
                      "note": "existing content at the old location is not moved"}, indent=2))
    return 0


# --------------------------------------------------------------------------- md repo

def cmd_md_status(project_dir: Path, path: str | None) -> int:
    ws = require_workstation(project_dir, path)
    if not ws.is_dir():
        raise WSError(f"workstation not found: {ws}")
    top = git_toplevel(ws)
    _, repo_name = remote_key(project_dir)
    if top is None:
        print(json.dumps({"git": False, "path": str(ws), "count": 0, "dirty": []}, indent=2))
        return 2
    real_top = Path(os.path.realpath(top))
    rel = Path(os.path.realpath(ws)).relative_to(real_top).as_posix() or "."
    proc = run_git(real_top, "status", "--porcelain=v1", "-z", "--untracked-files=all",
                   "--", rel)
    entries = proc.stdout.split("\0") if proc and proc.returncode == 0 else []
    dirty, skip = [], False
    for entry in entries:
        if skip:
            skip = False
            continue
        if not entry:
            continue
        dirty.append(entry[3:])
        skip = entry[0] in "RC"
    real_project = Path(os.path.realpath(project_dir))
    dedicated = (real_top != Path(os.path.realpath(Path.home()))
                 and not is_within(real_project, real_top))
    print(json.dumps({"git": True, "toplevel": str(real_top), "rel": rel,
                      "dedicated": dedicated,
                      "repo_name": repo_name or project_dir.name,
                      "count": len(dirty), "dirty": dirty}, indent=2))
    return 0 if dirty else 2


def cmd_grant_path(project_dir: Path, path: str | None) -> int:
    ws = require_workstation(project_dir, path)
    print(os.path.realpath(ws))
    return 0


# --------------------------------------------------------------------------- unlink

def cmd_unlink(project_dir: Path, dry_run: bool) -> int:
    settings = project_settings(project_dir)
    kept = settings.get("mdWorkstation")
    removed = unwire(project_dir, dry_run)
    actions = list(removed["actions"])
    for field in ("mdWorkstation", "mdLinks"):
        if field in settings:
            actions.append(f"remove {field} from {PROJECT_SETTINGS.as_posix()}")
    _kept_note(removed["exclude_kept"])
    if not actions:
        print("no workstation wiring found (no-op)", file=sys.stderr)
        return 2
    if not dry_run and ("mdWorkstation" in settings or "mdLinks" in settings):
        settings.pop("mdWorkstation", None)
        settings.pop("mdLinks", None)
        save_json(project_dir / PROJECT_SETTINGS, settings)
    print(json.dumps({"actions": actions, "kept": kept if kept != IN_REPO else None,
                      "exclude_kept": removed["exclude_kept"], "dry_run": dry_run}, indent=2))
    return 0


# --------------------------------------------------------------------------- cli

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Resolve and wire the md workstation (external home for Avengers + BMAD "
                    "markdown).",
        epilog="Exit codes: 0 = success, 1 = error, 2 = no-op.")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--project-dir", type=Path, default=Path("."),
                        help="Project root directory (default: current directory)")
    dry = argparse.ArgumentParser(add_help=False)
    dry.add_argument("--dry-run", action="store_true", help="Report without changing anything")
    ws_path = argparse.ArgumentParser(add_help=False)
    ws_path.add_argument("--path", help="Workstation path (default: the resolved workstation)")
    sub = parser.add_subparsers(dest="command", required=True)

    res = sub.add_parser("resolve", parents=[common], help="Report the workstation as JSON",
                         description="Print {state, path, source, root, remote_key, repo_name, "
                                     "suggested_path, output_folder, symlink, symlinks}. "
                                     "suggested_path is <root>/<repo_name>-mds. state: ok|guess|"
                                     "missing|broken|in_repo (broken when any managed link "
                                     "dangles). symlink is the output_folder link (kept for "
                                     "compatibility); symlinks maps each managed link (bmad, "
                                     "openspec) to ok|missing|dangling|mismatch|real_dir. "
                                     "Exit 0; 1 on error.")
    res.add_argument("--link", action="append", choices=LINKS, default=[],
                     help="Also report this link even if it is not managed yet (repeatable)")

    set_p = sub.add_parser("set", parents=[common, dry], help="Wire the workstation",
                           description="Create PATH/avengers/, record the project settings "
                                       "(mdWorkstation, mdLinks) and home registry, create each "
                                       "managed link's target and then the link (bmad: "
                                       "output_folder -> PATH; openspec: openspec/ -> "
                                       "PATH/openspec), add the .git/info/exclude lines, write "
                                       ".claude/rules/avengers-kb.md. --in-repo removes any "
                                       "symlink wiring and records the choice. Refuses a "
                                       "tracked or non-empty link folder (use migrate). "
                                       "Exit 0; 2 already set; 1 on error.")
    set_p.add_argument("--path", help="Workstation folder (default with --root: "
                                      "<root>/<repo-name>-mds)")
    set_p.add_argument("--root", help="md root to record in ~/.avengers/workstations.json "
                                      "(default: existing root, else the parent of --path)")
    set_p.add_argument("--in-repo", action="store_true",
                       help="Record that this project keeps its markdown in the repo")
    set_p.add_argument("--link", action="append", choices=LINKS, default=[],
                       help="Also manage this link (repeatable); recorded in mdLinks")

    mig = sub.add_parser("migrate", parents=[common, dry, ws_path],
                         help="Move an in-repo link folder into the workstation",
                         description="Move the link folder's contents (bmad: output_folder -> "
                                     "PATH; openspec: openspec/ -> PATH/openspec) into the "
                                     "workstation (differing name clashes keep both, as "
                                     "<name>.conflict<ext>), then run set with that link. "
                                     "Refuses a tracked folder without --untrack. Exit 0; 2 "
                                     "nothing to migrate; 1 on error.")
    mig.add_argument("--root", help="md root to record (as for set)")
    mig.add_argument("--untrack", action="store_true",
                     help="git rm -r --cached the tracked folder (left uncommitted)")
    mig.add_argument("--link", choices=LINKS, default="bmad",
                     help="Which link folder to migrate (default: bmad)")

    sub.add_parser("check-config", parents=[common],
                   help="List BMAD path keys outside output_folder as JSON",
                   description="Print {output_folder, outside: [{module, file, key, value, "
                               "resolved, suggested, declined}]} for the bmm and tea configs. "
                               "Exit 0 all inside; 2 some outside; 1 on error (_bmad/ "
                               "missing, or output_folder outside the project).")

    rep = sub.add_parser("repoint-config", parents=[common, dry],
                         help="Re-point one BMAD key under output_folder",
                         description="Rewrite KEY to {project-root}/<output_folder>/<key> in "
                                     "every config where it resolves outside, keeping inline "
                                     "comments; backs up to config.yaml.bak. --decline records "
                                     "the key in mdRepointDeclined instead. Exit 0; 2 no-op; "
                                     "1 on error.")
    rep.add_argument("--key", required=True, help="Config key, e.g. project_knowledge")
    rep.add_argument("--decline", action="store_true",
                     help="Record that the user declined re-pointing this key")

    sub.add_parser("md-status", parents=[common, ws_path],
                   help="Dirty files under the workstation in its md git repo",
                   description="Print {git, toplevel, rel, dedicated, repo_name, count, "
                               "dirty}. dedicated is false when the md repo is $HOME or "
                               "contains the project. Exit 0 dirty; 2 clean or not a git "
                               "repo; 1 on error.")
    sub.add_parser("grant-path", parents=[common, ws_path],
                   help="Print the workstation realpath for additionalDirectories",
                   description="Print the realpath of the workstation. Exit 0; 1 on error.")
    sub.add_parser("kb-rules", parents=[common, dry],
                   help="(Re)write .claude/rules/avengers-kb.md",
                   description="Write the search hint and, once <workstation>/project-context"
                               ".md exists, its @import. Exit 0 written; 2 up to date; 1 no "
                               "workstation recorded.")
    sub.add_parser("unlink", parents=[common, dry],
                   help="Remove the symlinks, project settings, avengers-kb.md and exclude "
                        "lines",
                   description="Removes every managed link's symlink (never a real directory "
                               "or the openspec/ content behind it), mdWorkstation and mdLinks. "
                               "Exclude lines another worktree still uses are kept (reported "
                               "in exclude_kept). Never touches the workstation contents or "
                               "the home registry. Exit 0; 2 nothing to remove; 1 on error.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if sys.platform == "win32":
        print("ERROR: the md workstation needs directory symlinks; Windows is not supported",
              file=sys.stderr)
        return 1
    project_dir = Path(os.path.normpath(args.project_dir.expanduser().absolute()))
    if not project_dir.is_dir():
        print(f"ERROR: project directory not found: {project_dir}", file=sys.stderr)
        return 1
    try:
        if args.command == "resolve":
            print(json.dumps(resolve(project_dir, tuple(args.link)), indent=2))
            return 0
        if args.command == "set":
            return cmd_set(project_dir, args.path, args.root, args.in_repo, args.dry_run,
                           tuple(args.link))
        if args.command == "migrate":
            return cmd_migrate(project_dir, args.path, args.root, args.untrack, args.dry_run,
                               args.link)
        if args.command == "check-config":
            return cmd_check_config(project_dir)
        if args.command == "repoint-config":
            return cmd_repoint(project_dir, args.key, args.decline, args.dry_run)
        if args.command == "md-status":
            return cmd_md_status(project_dir, args.path)
        if args.command == "grant-path":
            return cmd_grant_path(project_dir, args.path)
        if args.command == "kb-rules":
            return cmd_kb_rules(project_dir, args.dry_run)
        return cmd_unlink(project_dir, args.dry_run)
    except (WSError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
