#!/usr/bin/env python3
"""
avengers-init.py - Full environment setup for Avengers Dev.

Creates:
  - .avengers/settings.json (project config)
  - .claude/rules/avengers-dev.md (auto-loaded by Claude Code, activates IronMan)
  - .avengers/relay-sequences/ (directory for BMAD state files)

Exit codes:
  0 = success
  1 = error
  2 = already initialized (no-op)
"""
import argparse
import json
import sys
from pathlib import Path


RULES_FILE_TEMPLATE = """\
# Avengers Dev - Active Rules
# Generated by /avengers-init - do not edit manually.
# Re-generate with /avengers-init. Machine-specific (gitignore this file).

@include {persona_path}
@include {delegation_path}
"""

SETTINGS_TEMPLATE = {
    "version": "1.0.0",
    "pluginDirectory": "",
    "initialized": True,
}


def write_if_changed(path: Path, content: str) -> bool:
    """Write file only if content differs. Returns True if written."""
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main():
    parser = argparse.ArgumentParser(description="Initialize Avengers Dev for a project")
    parser.add_argument("--plugin-dir", type=Path, required=True, help="Plugin root directory")
    parser.add_argument("--project-dir", type=Path, default=Path("."), help="Project root directory")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be done without writing")
    args = parser.parse_args()

    plugin_dir = args.plugin_dir.resolve()
    project_dir = args.project_dir.resolve()

    if not plugin_dir.exists():
        print(f"ERROR: Plugin directory not found: {plugin_dir}", file=sys.stderr)
        sys.exit(1)

    # Check if already initialized
    settings_path = project_dir / ".avengers" / "settings.json"
    rules_path = project_dir / ".claude" / "rules" / "avengers-dev.md"

    if settings_path.exists() and rules_path.exists():
        print(f"Already initialized (no-op). Re-run with --force to overwrite.", file=sys.stderr)
        sys.exit(2)

    # Paths for rules file
    persona_path = plugin_dir / "personas" / "ironman.md"
    delegation_path = plugin_dir / ".claude" / "rules" / "ironman-delegation.md"

    # Build content
    settings_content = json.dumps({
        **SETTINGS_TEMPLATE,
        "pluginDirectory": str(plugin_dir),
    }, indent=2)

    rules_content = RULES_FILE_TEMPLATE.format(
        persona_path=persona_path,
        delegation_path=delegation_path,
    )

    gitignore_entry = ".claude/rules/avengers-dev.md\n"

    if args.dry_run:
        print(f"Would write: {settings_path}")
        print(f"Would write: {rules_path}")
        print(f"Would create: {project_dir / '.avengers' / 'relay-sequences'}/")
        print(f"Would add to .gitignore: {gitignore_entry.strip()}")
        sys.exit(0)

    # Write settings.json
    (project_dir / ".avengers").mkdir(parents=True, exist_ok=True)
    settings_path.write_text(settings_content)
    print(f"Created: {settings_path.relative_to(project_dir)}")

    # Write rules file
    write_if_changed(rules_path, rules_content)
    print(f"Created: {rules_path.relative_to(project_dir)}")

    # Create relay-sequences directory
    relay_dir = project_dir / ".avengers" / "relay-sequences"
    relay_dir.mkdir(parents=True, exist_ok=True)
    print(f"Created: {relay_dir.relative_to(project_dir)}/")

    # Add avengers-dev.md to .gitignore
    gitignore_path = project_dir / ".gitignore"
    if gitignore_path.exists():
        content = gitignore_path.read_text()
        if ".claude/rules/avengers-dev.md" not in content:
            with open(gitignore_path, "a") as f:
                f.write(f"\n# Avengers Dev (machine-specific, auto-generated)\n{gitignore_entry}")
            print(f"Updated: .gitignore (added avengers-dev.md entry)")
    else:
        gitignore_path.write_text(f"# Avengers Dev (machine-specific, auto-generated)\n{gitignore_entry}")
        print(f"Created: .gitignore")

    print(f"\nAvengers Dev initialized. IronMan active on next session start.")
    sys.exit(0)


if __name__ == "__main__":
    main()
